import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, } from "@clerk/nextjs";
import Provider from "./Provider";
import {Outfit} from "next/font/google"

export const metadata: Metadata = {
  title: "ShortGen",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']})

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <ClerkProvider >
      <html lang="en">
        <body
          className={outfit.className}
          >
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
